
'use client'

import "./globals.css";
// import type { Metadata } from "next";
import React from "react";
import { ThemeProvider } from "@/providers/ThemeProvider";
import { Inter } from "next/font/google";

import {
  QueryClient,
  QueryClientProvider,
} from "@tanstack/react-query";

import { Layout } from "@/components/index";

import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [queryClient] = React.useState(() => new QueryClient())
  
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider attribute="class" defaultTheme="dark" enableSystem>
          <QueryClientProvider client={queryClient}>
            <Layout>{children}</Layout>
          </QueryClientProvider>
        </ThemeProvider>
        <ToastContainer theme="dark" />
      </body>
    </html>
  );
}
